 "use client";
import { motion } from "framer-motion";
import { Megaphone, Search, Code2, Share2, Users, Target, CheckCircle2, ArrowRight } from "lucide-react";
const services=[["Meta Ads Management","High-converting Meta campaigns built around precise audiences and creative testing.",Megaphone],["Google Ads Management","Capture high-intent demand with optimized search and performance campaigns.",Target],["SEO Services","Build sustainable organic visibility with technical, on-page and content SEO.",Search],["Website Development","Fast, conversion-focused websites designed to turn traffic into customers.",Code2],["Social Media Marketing","Consistent social strategy, content and community growth for your brand.",Share2],["Lead Generation","Predictable lead pipelines using paid, organic and landing-page systems.",Users]];
const why=["Experienced Team","Transparent Reporting","Affordable Pricing","ROI Focused Strategies","Dedicated Support","Proven Results"];
const process=["Consultation","Research","Strategy","Execution","Optimization","Growth"];
const projects=[["Nova Interiors","Interior Design","Website","+63% qualified enquiries"],["UrbanFit","Fitness","Social Media","3.2x engagement growth"],["FinEdge","Finance","SEO","+148% organic traffic"],["Apex Homes","Real Estate","Ads","5.8x ROAS"]];
export function Stats(){return <section className="border-y bg-white"><div className="container-x grid grid-cols-2 gap-8 py-10 md:grid-cols-4">{[["500+","Leads Generated"],["100+","Happy Clients"],["5+","Years Experience"],["95%","Client Retention"]].map(([a,b])=><div key={b} className="text-center"><div className="text-4xl font-black text-brand-red">{a}</div><div className="mt-1 text-sm text-gray-500">{b}</div></div>)}</div></section>}
export function Services(){return <section id="services" className="section bg-gray-50"><div className="container-x"><div className="max-w-2xl"><p className="font-bold text-brand-red">WHAT WE DO</p><h2 className="mt-2 text-4xl font-black md:text-5xl">Marketing systems built for measurable growth.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map(([t,d,I])=><motion.div whileHover={{y:-7}} key={t as string} className="rounded-3xl border bg-white p-7 shadow-sm"><div className="mb-6 inline-flex rounded-2xl bg-red-50 p-4 text-brand-red">{I && <I/>}</div><h3 className="text-xl font-black">{t as string}</h3><p className="mt-3 leading-7 text-gray-600">{d as string}</p><button className="mt-6 font-bold text-brand-red">Learn More <ArrowRight className="ml-1 inline" size={16}/></button></motion.div>)}</div></div></section>}
export function Why(){return <section id="about" className="section"><div className="container-x grid gap-14 lg:grid-cols-2"><div><p className="font-bold text-brand-red">WHY VISHAL MEDIA TECH</p><h2 className="mt-2 text-4xl font-black md:text-5xl">A growth partner, not just another agency.</h2><p className="mt-6 leading-8 text-gray-600">We connect strategy, creative, technology and analytics into one focused growth engine. Every campaign is measured against business outcomes.</p></div><div className="grid grid-cols-2 gap-4">{why.map(x=><div key={x} className="rounded-2xl border bg-gray-50 p-5 font-bold"><CheckCircle2 className="mb-3 text-brand-red"/>{x}</div>)}</div></div></section>}
export function Process(){return <section className="section bg-gray-50"><div className="container-x"><div className="text-center"><p className="font-bold text-brand-red">OUR PROCESS</p><h2 className="mt-2 text-4xl font-black">From first call to scalable growth.</h2></div><div className="mt-14 grid gap-5 md:grid-cols-3 lg:grid-cols-6">{process.map((x,i)=><div key={x} className="relative rounded-2xl bg-white p-5 text-center shadow-sm"><div className="mx-auto mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-brand-red font-black text-white">{i+1}</div><b>{x}</b></div>)}</div></div></section>}
export function Portfolio(){return <section id="portfolio" className="section"><div className="container-x"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-bold text-brand-red">SELECTED WORK</p><h2 className="mt-2 text-4xl font-black">Results that speak.</h2></div></div><div className="mt-12 grid gap-6 md:grid-cols-2">{projects.map(([n,i,c,r],idx)=><motion.div whileHover={{y:-5}} key={n} className="overflow-hidden rounded-3xl border bg-white"><div className="h-52 bg-gradient-to-br from-gray-900 via-gray-700 to-red-700 p-8 text-white"><span className="rounded-full bg-white/15 px-3 py-1 text-xs">{c}</span><div className="mt-20 text-3xl font-black">{n}</div></div><div className="p-6"><p className="text-sm text-gray-500">{i} · {c}</p><p className="mt-2 text-xl font-black text-brand-red">{r}</p></div></motion.div>)}</div></div></section>}
export function Testimonials(){return <section className="section bg-gray-50"><div className="container-x"><div className="text-center"><p className="font-bold text-brand-red">CLIENT LOVE</p><h2 className="mt-2 text-4xl font-black">Trusted by ambitious businesses.</h2></div><div className="mt-12 grid gap-6 md:grid-cols-3">{[["Rohit Sharma","Founder, Nova Interiors","The team transformed our lead flow. Reporting is clear and the results are real."],["Ananya Verma","Director, UrbanFit","Excellent communication, fast execution and a strong understanding of performance marketing."],["Aman Gupta","CEO, FinEdge","Our organic traffic has grown consistently since the SEO program started."]].map(([n,c,r])=><div key={n} className="rounded-3xl bg-white p-7 shadow-sm"><div className="text-lg text-yellow-500">★★★★★</div><p className="mt-5 leading-7 text-gray-700">“{r}”</p><div className="mt-6"><b>{n}</b><p className="text-sm text-gray-500">{c}</p></div></div>)}</div></div></section>}
export function FAQ(){return <section className="section"><div className="container-x max-w-4xl"><div className="text-center"><p className="font-bold text-brand-red">FAQ</p><h2 className="mt-2 text-4xl font-black">Questions, answered.</h2></div><div className="mt-10 space-y-3">{["How much do Meta Ads and Google Ads cost?","How long does SEO take to show results?","Do you build custom websites?","Can you generate leads for my business?","How do you report campaign performance?"].map(q=><details key={q} className="rounded-2xl border p-5"><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-3 leading-7 text-gray-600">We tailor the plan to your goals, market and budget. During the consultation we define measurable targets, timelines and the reporting cadence before work begins.</p></details>)}</div></div></section>}
